# Generated by Django 4.0.2 on 2022-02-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('roll', models.IntegerField()),
                ('address', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
